### ISSUE TITLE
support edge?

### ISSUE THREAD

**Issue by mmcdaris** [mssola/user_agent#19]
Any chance to get edge support?
An example user agent string looks like:
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240
```
Thanks for the cool package :D

**Comment by mssola** [comment]
Thank you @mmcdaris for the heads up :)

**Comment by mmcdaris** [comment]
Thanks! Good job on the speedy close!
