### ISSUE TITLE
Edge Detecting as Chrome

### ISSUE THREAD

**Issue by moonmeister** [mssola/user_agent#36]
In using this on the Mattermost project we have found that it detects Edge as Chrome. I'm not sure if it's limited to a certain version of Edge or all Edge versions. The version I'm running is Edge 38.xxxx (EdgeHTML 14.xxx). It's detecting as Chrome 51.

Is this a known issue or bug? Either way can we do anything to help resolve it? Thanks.

**Comment by mssola** [comment]
Could you write the given user-agent string ? (sorry for the late response, I was on vacation 😁)

**Comment by moonmeister** [comment]
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393

**Comment by mssola** [comment]
I cannot reproduce it. I've run the following code with master:

```go
package main

import (
	"fmt"

	"github.com/mssola/user_agent"
)

func main() {
	ua := user_agent.New("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393")
	fmt.Printf("%#v\n", ua)
}
```

The given result is correct:

```
mssola:~ $ go run test.go 
&user_agent.UserAgent{ua:"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393", mozilla:"5.0", platform:"Windows", os:"Windows 10", localization:"", browser:user_agent.Browser{Engine:"EdgeHTML", EngineVersion:"", Name:"Edge", Version:"14.14393"}, bot:false, mobile:false, undecided:false}
```

Are you using master ? Moreover, note that a fix for Edge was introduced in f659b9863849e0350d7f3e9c8070121163c54acd.

**Comment by moonmeister** [comment]
@mssola Ah, thanks yeah I assumed @mattermost was using the latest version. I'll check what version we are using and get back to you. Thanks for the help.

**Comment by moonmeister** [comment]
@mssola Yeah, I've confirmed we were on the latest tagged version which looks to be 3+ years old. I've done tests with the master branch and everything works. Thanks.

**Comment by mssola** [comment]
@moonmeister  Currently the master branch is supposed to be stable, so using it should be safe.
