### ISSUE TITLE
release a new tagged version

### ISSUE THREAD

**Issue by pierrre** [mssola/user_agent#47]
Hello !

Could you release a new tagged version ?
There are many changes since the latest tag: https://github.com/mssola/user_agent/compare/v0.4.1...master

Do you have any plan to release future tags more frequently ?
Do you use semver ?

Thank you.

**Comment by mssola** [comment]
> Could you release a new tagged version ?

Sure thing

> Do you have any plan to release future tags more frequently ?

Not really. Once some fixes accumulate, I make a new release. That being said, lately I've been slacking off a bit, apparently... :sweat_smile: 

> Do you use semver ?

To the best of my knowledge I do :smile:

**Comment by mssola** [comment]
Done: https://github.com/mssola/user_agent/releases/tag/v0.5.0. Thanks for the heads up :+1:

**Comment by pierrre** [comment]
@mssola thank you ! :+1:
