### ISSUE TITLE
Support of Microsoft Edge is missing

### ISSUE THREAD

**Issue by asinha08** [mssola/user_agent#69]
### Description

Support of Microsoft Edge is missing

### Steps to reproduce

1. Get UA from Microsoft Edge

- Browser name = "Edge"
- currently getting Browser name = "Chrome"

### user_agent version

With a git commit SHA if possible.

### Go version and interpreter

```bash
$ go version
```

### Operating system

The operating system and the exact version you are using. If you are using Linux, it may be useful to know which distribution you are using and what did you do in order to install go.

**Comment by mssola** [comment]
Could you provide the full user agent as given by this browser?

**Comment by asinha08** [comment]
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36 Edg/84.0.522.40

**Comment by DanMHammer** [comment]
Made PR to address this: https://github.com/mssola/user_agent/pull/70
