### ISSUE TITLE
Package name should be useragent, not user_agent

### ISSUE THREAD

**Issue by peterbourgon** [mssola/user_agent#73]
>  By convention, packages are given lower case, single-word names; there should be no need for underscores . . . 

https://golang.org/doc/effective_go.html#package-names

> Good package names . . . are lower case, with no under_scores or mixedCaps.

https://blog.golang.org/package-names

**Comment by peterbourgon** [comment]
You're still on major version 0, it shouldn't be a problem.

**Comment by prologic** [comment]
@mssola I'm considering using your library in one of my projects, but I'd really like you to rename the package please if you're okay with this. Breaking the [~200 something imports](https://pkg.go.dev/github.com/mssola/user_agent?tab=importedby) 😳 won't be a big deal if you fork the codebase into a v2 package or something similar which I've seen other projects do.

Can we do that? 🤔

**Comment by mssola** [comment]
Done. See: https://github.com/mssola/useragent
