### ISSUE TITLE
Why remove func (p *UserAgent) Model() string

### ISSUE THREAD

**Issue by slifer2015** [mssola/user_agent#86]
I see that in thew latest version you removed 
`func (p *UserAgent) Model() string{
	return p.model
}`

Is there any alternative to get model ?

**Comment by tmc** [comment]
This makes the readme inaccurate as well.

**Comment by shubhamSingh-sib** [comment]
Any updates ? The code present on the `master` branch still supports the aforementioned method but the latest release doesn't.

**Comment by mssola** [comment]
Fixed this issue, see latest release https://github.com/mssola/user_agent/releases/tag/v0.6.0
